### ISSUE TITLE
Sort by suggestion

### ISSUE THREAD

**Issue by Chaprnks** [markski1/SAMonitor#2]
**TL;DR:**
Filter by language

**Long version:**
Now that there's finally a SACNR clone with an active development; I can suggest something I've wanted since SA-MP 0.1b in 2007. With the boom in global playerbase; filtering the servers by your own language can be exceptionally difficult. If need be, I'd be more than happy to write the pull request myself, if timing/manpower is an issue.

**Filter feature:**
Sort by language {string}

**Example:**
![OzAawWN](https://github.com/markski1/SAMonitor/assets/6340970/5126ca11-6e7e-4295-a471-ba2cf8d479d4)

**Comment by markski1** [comment]
Luckily, just today I added an API endpoint for language sorting. This will be added to the website soon.

**Comment by markski1** [comment]
This feature has been added and is now live.

![imagen](https://github.com/markski1/SAMonitor/assets/22557859/523e6427-4e13-483c-b9eb-e1f052e4959f)
