### ISSUE TITLE
[Question] NuGet

### ISSUE THREAD

**Issue by J0nathan550** [markski1/SAMonitor#4]
Can you add in the future or soon the NuGet package of your API?

**Comment by markski1** [comment]
Hello, what would you like a NuGet package for?

SAMonitor is a standalone application, not a library, but please explain what you want to do

**Comment by J0nathan550** [comment]
Well, can't your project be converted to library so everyone could easily access files through nuget than downloading everything from Github?

**Comment by J0nathan550** [comment]
I'm very sorry, I just understand that your project is specifying the standalone ASP.NET Core web app, What I wanted is to have an API to use for WPF or Forms to retrieve some data, if you could do that I would be much appreciated to have access to do that, I will try to do workaround to use the API for different types of apps.

**Comment by markski1** [comment]
Hello Jonathan, sorry for my delay. If you want to use the SAMonitor API you'll have to use it through the endpoints in README.md but if what you want is a NuGet package to query samp servers, please look at SAMPQuery, which is available in NuGet.

https://github.com/justmavi/sampquery

The querying mechanism in SAMonitor is built on this library too.

**Comment by J0nathan550** [comment]
Hey, this API that you send is good, but it misses the part of getting list of all servers online, using your website with JSON I managed to pull all of the online servers in SAMP. I will try to contribute my solution onto how to get the list of all online servers.

**Comment by markski1** [comment]
If you ONLY want online servers, make sure to pull from the `GetFilteredServers` endpoint instead of the `GetAllServers`. FilteredServers by default removes servers which are offline

**Comment by J0nathan550** [comment]
Oh snap, I will try to list through FilterServers then, also change little bit the Pull Request in: https://github.com/justmavi/sampquery/pull/12
